// src/enums/roles.enum.ts
export enum UserRole {
    DIRECTORA = 'DIRECTORA',
    SECRETARIA = 'SECRETARIA',
    DOCENTE = 'DOCENTE',
    APODERADO = 'APODERADO',
    ESTUDIANTE = 'ESTUDIANTE',
    COORDINADOR = 'COORDINADOR',
    AUXILIAR = 'AUXILIAR',
    PSICOLOGO = 'PSICOLOGO',
}