export enum TipoObservacionDocente {
    PROGRAMACION_TARDIA = 'PROGRAMACION_TARDIA',
    AUSENCIA_INJUSTIFICADA = 'AUSENCIA_INJUSTIFICADA',
    INCUMPLIMIENTO_HORARIO = 'INCUMPLIMIENTO_HORARIO',
    FALTA_MATERIAL_DIDACTICO = 'FALTA_MATERIAL_DIDACTICO',
    METODOLOGIA_INADECUADA = 'METODOLOGIA_INADECUADA',
    EVALUACION_DEFICIENTE = 'EVALUACION_DEFICIENTE',
    COMPORTAMIENTO_INADECUADO = 'COMPORTAMIENTO_INADECUADO',
    OTRO = 'OTRO'
}
